### ISSUE TITLE
Error while running django-tutelary example project

### ISSUE THREAD

**Issue by eomwandho** [Cadasta/django-tutelary#16]
When I run the example project under django-tutelary to figure how it handles policy based permission. I get the stack trace below.

https://gist.github.com/eomwandho/aaf59f72c62105cf3291

**Comment by ian-ross** [comment]
What version of Python are you using?  django-tutelary is Python 3.3+ only.

**Comment by eomwandho** [comment]
Python 2.7. 

It was an oversight, I have seen from the website that it's only supports 3.3+

I thought it would be backward compatible with 2.7

Thanks anyway!

**Comment by ian-ross** [comment]
It's probably best to think of Python 2 and Python 3 as completely different languages.  I know that people write code that's compatible with both, but for us it's not worth the effort.  And Python 3 has some nice features like generator comprehensions and `yield from` (which was what caused the error you saw).  I'd rather not have to work around the lack of those things.
