### ISSUE TITLE
Feedback on documentation

### ISSUE THREAD

**Issue by seav** [Cadasta/django-tutelary#22]
_**Note:** I'm assuming that the [published documentation](http://www.skybluetrades.net/django-tutelary) more or less corresponds to the source here in GitHub._

Initial batch of comments, corrections, and questions _(I will add additional items as I continue reading the documentation)_:
 
1. **General:** Some code examples have syntax highlighting while others don't?
2. **Permissioning models:** In the first code example, the `path_fields` is set to `('project', 'pk')` but in the prose after the code, the reference to the object is `party/.../<name>`. I think this should be `party/.../<pk>` instead.
3. **Permissions for views:** (grammar) "this can simply *by* mixed" should be "this can simply be mixed".
4. **Permissions for views:** In the code example, the `patch_actions` method does not match the required signature of `method_name(self, view, request)`.
5. **General:** Make use of "organization" vs. "organisation" consistent. In code, it seems everything is consistently using 'z', but in prose, there are instances of both. 
6. **Policy definitions:** Quote: “`["parcel.create", "parcel.delete"]` refers to the create and delete actions for `parcel` objects.” But this is just by user convention, right? Tutelary does not really care if `parcel` really refers to objects of a `Parcel` model. I could use `parcel.create` as a required permission in a view that's totally unrelated to parcels (although it would be confusing) and it would still work.
7. **Policy composition and assignment:** I assume that most of the code examples here goes into some one-off setup-type scripts? Should this be explicitly stated?
8. **Policy composition and assignment:** What happens if policy template variables are missing or superfluous?

**Comment by ian-ross** [comment]
Thanks for the comments!

 - [ ] Syntax highlighting problems.
 - [ ] Path field references in "Permissioning models".
 - [ ] Grammar in "Permissions for views".
 - [ ] "Permissions for views": `patch_actions` signature wrong.
 - [ ] "Organization" vs. "organisation". 
 - [ ] Action labels are arbitrary -- make this clear.
 - [ ] Code examples -- make it clear they're "freestanding" (they're just example snippets, and don't go with any setup scripts or anything; there's a whole example application to demonstrate the package in use).
 - [ ] Comments on missing or superfluous policy template variables.

**Comment by ian-ross** [comment]
I decided not to say anything about the code samples being just free-standing examples.  There's a lot of other "real" example code in the example application for people to look at.
