### ISSUE TITLE
Compile error on "JSONDecodeError"

### ISSUE THREAD

**Issue by seav** [Cadasta/django-tutelary#23]
While trying out the example application, I get the following error when performing the initial migration:

```
...
  File "/<path>/django-tutelary/tutelary/engine.py", line 4, in <module>
    from json import loads, dumps, JSONDecodeError
ImportError: cannot import name 'JSONDecodeError'
```

 I temporarily removed `JSONDecodeError` from the import line and the migration succeeded. Based on Googling, it seems that there is no need to explicitly import `JSONDecodeError`?

**Comment by ian-ross** [comment]
This usually happens when you're using an older Python version. Do you have Python 3.5? Python 3.4 has the JSON modules set up slightly differently.

**Comment by seav** [comment]
I see. I only had 3.4 installed. I didn't realize that there would be such differences between the two versions. I was able to install 3.5 using an unofficial PPA (because my OS version didn't have the 3.5 packages) and I confirm that the compile error no longer occurs.
