### ISSUE TITLE
Use Django caching framework

### ISSUE THREAD

**Issue by ian-ross** [Cadasta/django-tutelary#32]
At the moment, there is ad hoc caching of `WildTree` structures and permission sets created from policy composition when assigning policies to users.  This caching is done mostly just using `functools.lru_cache`, which is not appropriate for a multi-process setup (like we use with UWSGI in production for Cadasta/cadasta-platform).  Instead, this caching should be done using the Django cache framework.  We can then use `memcached` for caching in production, which will remove any issues to do with multi-process cache invalidation.

(I'd consider this a bug, because it means that it's possible to get inconsistent views of a user's permissions depending on the random assignment of your HTTP request to one of UWSGI's worker processes.)

**Comment by amplifi** [comment]
Completed; Django cache framework has been implemented with memcached in production.
