### ISSUE TITLE
Making individual apps and include their respective urls file in order to shorten urls.py!!!

### ISSUE THREAD

**Issue by modestlearner** [Cadasta/django-tutelary#37]
I want to make separate apps for each component and then include their urls.py file in order to reduce the code in main urls file and thus make it more readable and efficient.

I want to work on this if I am not interrupting the workflow

**Comment by oliverroick** [comment]
Hi @modestlearner, thank you for your interest in the project. 

I'm assuming that you are talking about the example app. While separating components in different apps is certainly something that would be feasible but I'm not sure if it's worth your time. I think the code is still manageable as it is and it's unlikely that we will extend the example app anytime soon. It's more likely that we are discontinuing tutelary towards the end of the year.

**Comment by modestlearner** [comment]
Yes I am talking about the example app.
The code is indeed manageable but still it can be a bit cumbersome in future.
I'll be glad to work on this issue as I am new to open source and this community.
Please do help me as I am just a beginner in open source :D

**Comment by oliverroick** [comment]
Look, there's no way for us to prevent you from working on this ticket. I just don't want you to waste your time on a library that might be abandoned soon. Maybe it's better if you invest time in a more active project with a more secure future than this django-tutelary. 

If you still want to work on this, then I'd suggest you fork the project, build a prototype how you think it should be implemented and then open a pull request so we can discuss how to proceed.

**Comment by modestlearner** [comment]
Oh !!!!!
Okay fine no problem I will not do anything since this repo will be abandoned soon.
Thank you !!!
