### ISSUE TITLE
Implement full Django admin interface

### ISSUE THREAD

**Issue by ian-ross** [Cadasta/django-tutelary#7]
This might be quite a bit of work, but a lot of people use the Django admin pages, so django-tutelary really ought to support it.  Probably start by copying the admin stuff for `django.contrib.auth`?

**Comment by TroJan** [comment]
@ian-ross : this involves creating __ModelAdmin__ class for each model in `tutelary/models.py` with some basic options like `list_display` and all ?

**Comment by ian-ross** [comment]
Not sure.  I've never done anything with the Django admin.  I never use it.  But I know other people like it, which is why I opened this issue.

In any case, to do a decent job of this for django-tutelary, a bit more than "normal" admin views would be needed, I think.  There would need to be custom views for testing permissions (with introspection into the available Django models using `ContentType` to allow users to pick instances of models to test permissions against) and probably some structured way of viewing the `WildTree` search trees that result from composing policies into `PermissionSet` instances.

Without those things, I'm not sure that the normal Django admin views would be all that useful, though if you want to give it a go, even the basic views would be a start.
